from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import re
from datetime import datetime


def clean_text(text):
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = text.replace('&', '&amp;').replace('<b>', '<b>').replace('</b>', '</b>')
    return text


def create_pdf_report(topic, content, filename=None):
    if filename is None:
        safe_topic = re.sub(r'[^\w\s-]', '', topic)[:30].strip()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{safe_topic}_{timestamp}.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=1 * inch,
        bottomMargin=0.75 * inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=HexColor('#1a1a2e'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#666666'),
        spaceAfter=20,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=HexColor('#1a1a2e'),
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold'
    )

    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=HexColor('#333333'),
        spaceBefore=10,
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#333333'),
        spaceAfter=8,
        leading=18,
        alignment=TA_LEFT
    )

    bullet_style = ParagraphStyle(
        'CustomBullet',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor('#333333'),
        spaceAfter=5,
        leading=16,
        leftIndent=20
    )

    story = []

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Research Report", title_style))
    story.append(Paragraph(topic.title(), subtitle_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=HexColor('#1a1a2e')))
    story.append(Spacer(1, 0.2 * inch))

    lines = content.split('\n')

    for line in lines:
        line = line.strip()
        if not line or line == '---':
            story.append(Spacer(1, 0.1 * inch))
            continue

        if line.startswith('### '):
            heading_text = line.replace('### ', '')
            heading_text = re.sub(r'\*\*(.*?)\*\*', r'\1', heading_text)
            story.append(Paragraph(heading_text, subheading_style))

        elif line.startswith('## '):
            heading_text = line.replace('## ', '')
            heading_text = re.sub(r'\*\*(.*?)\*\*', r'\1', heading_text)
            story.append(Paragraph(heading_text, heading_style))
            story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor('#cccccc')))

        elif line.startswith('* ') or line.startswith('- '):
            bullet_text = line[2:]
            bullet_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', bullet_text)
            bullet_text = bullet_text.replace('&', '&amp;')
            story.append(Paragraph(f"• {bullet_text}", bullet_style))

        else:
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            clean_line = clean_line.replace('&', '&amp;')
            story.append(Paragraph(clean_line, body_style))

    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#1a1a2e')))
    story.append(Paragraph("Generated by Personal Research Agent", subtitle_style))

    doc.build(story)
    print(f"✅ PDF saved as: {filename}")
    return filename


if __name__ == "__main__":
    test_content = """
## Overview
This is a test report to verify PDF generation is working correctly.

## Key Findings
* **Finding one** is very important
* **Finding two** provides additional context
* Finding three rounds out the analysis

## Conclusion
The PDF generation is working perfectly and ready for use.
"""
    create_pdf_report("Test Topic", test_content)